export const VALIDATE_USER = "VALIDATE_USER";
export const USER_VALIDATED_SUCCESSFULLY =
  "[API RESPONSE] USER_VALIDATED_SUCCESSFULLY";
export const USER_VALIDATION_FAILED = "[API RESPONSE] USER_VALIDATION_FAILED";
export const REMEMBER_ME = "[LOGIN UI] REMEMBER_ME";
export const SIGN_OUT_LOGGEDIN_USER = "[HEADER BUTTON] SIGN_OUT_LOGGEDIN_USER";
