export const LOAD_PRODUCT_LIST = "[API REQUEST] LOAD_PRODUCT_LIST";
export const PRODUCT_LOADED_SUCCESSFULLY =
  "[API RESPONSE] PRODUCT_LOADED_SUCCESSFULLY";
export const PRODUCT_LOAD_FAILED = "[API RESPONSE] PRODUCT_LOAD_FAILED";
export const UPDATE_ADD_TO_CART = "[PRODUCT LIST] UPDATE_ADD_TO_CART";
