export const LOAD_FILTER_INFORMATION = "[FILTER LIST] LOAD_FILTER_INFORMATION";
export const FILTER_LOADED_SUCCESSFULLY =
  "[FILTER API RESPONSE] FILTER_LOADED_SUCCESSFULLY";
export const FILTERS_FAILED_TO_LOAD =
  "[FILTER API RESPONSE] FILTERS_FAILED_TO_LOAD";
export const UPDATE_BRAND_FILTER_OPTION =
  "[FILTER LIST] UPDATE_BRAND_FILTER_OPTION";
export const UPDATE_COLOUR_FILTER_OPTION =
  "[FILTER LIST] UPDATE_COLOUR_FILTER_OPTION";

export const UPDATE_PRICE_FILTER_OPTION =
  "[FILTER LIST] UPDATE_PRICE_FILTER_OPTION";
